### ISSUE TITLE
JDBC Error when attempting connect to Database

### ISSUE THREAD

**Issue by saatviks** [bloomberg/comdb2#553]
1. I've obtained the jar file using `./gradlew install` in the `cdb2jdbc` directory in the project source.
2. When attempting to connect, via Java I get the following log:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.<init>(Comdb2Handle.java:166)
	at com.bloomberg.comdb2.jdbc.Comdb2Connection.<init>(Comdb2Connection.java:103)
	at com.bloomberg.comdb2.jdbc.Comdb2Connection.<init>(Comdb2Connection.java:89)
	at com.bloomberg.comdb2.jdbc.Driver.connect(Driver.java:213)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:119)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:292)
	at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:799)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:539)
```

Just FYI, as part of an assignment in my coursework I'm attempting to benchmark ComDB2 via [OLTPBench](https://github.com/oltpbenchmark/oltpbench) which is why you see the DBWorkload statements in the log.

**Comment by riverszhang89** [comment]
You'd need protobuf-java v3.2.0 as well. We highly recommend that you use gradle or maven to build your applications such that the correct dependencies will be automatically pulled in. If you'd like to use the jar file directly, we recommend you add the [uber jar](https://bloomberg.github.io/comdb2/jdbc_api.html#setting-the-classpath) to CLASSPATH instead.

**Comment by saatviks** [comment]
I noticed that the `build.gradle` already contains the protobuf-java dependency mentioned in it.
I think the problem is that I'm not using the uber jar(`cdb2jdbc-<version>-shaded.jar`). The thing is running `./gradlew install` or `gradle build` only generates `build/libs/cdb2jdbc-2.0.0.jar`. How do I generate the uber jar?

**Comment by riverszhang89** [comment]
It looks like our gradle build does not support building a uber jar yet. Nevertheless You should be able to find protobuf-java library under `~/.m2/repository/com/google/protobuf/protobuf-java/` and the jar to CLASSPATH.

**Comment by saatviks** [comment]
Yes, that resolved that problem.
Now, I'm facing a new error.
```
Caused by: java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessageLite$Builder.addAll(Ljava/lang/Iterable;Ljava/util/List;)V
	at com.bloomberg.comdb2.jdbc.Sqlquery$CDB2_SQLQUERY$Builder.addAllFeatures(Sqlquery.java:6159)
	at com.bloomberg.comdb2.jdbc.ProtobufProtocol.pack(ProtobufProtocol.java:203)
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.sendQuery(Comdb2Handle.java:617)
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.runStatementInt(Comdb2Handle.java:939)
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.runStatement(Comdb2Handle.java:1342)
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.runStatement(Comdb2Handle.java:751)
	at com.bloomberg.comdb2.jdbc.Comdb2Statement.executeQuery(Comdb2Statement.java:118)
	at com.bloomberg.comdb2.jdbc.Comdb2Statement.executeQuery(Comdb2Statement.java:70)
	at com.bloomberg.comdb2.jdbc.Comdb2Statement.executeUpdate(Comdb2Statement.java:157)
	at com.bloomberg.comdb2.jdbc.Comdb2PreparedStatement.executeUpdate(Comdb2PreparedStatement.java:132)
	at com.bloomberg.comdb2.jdbc.Comdb2PreparedStatement.executeBatch(Comdb2PreparedStatement.java:437)
	at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader.loadItems(TPCCLoader.java:202)
	at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader$1.load(TPCCLoader.java:85)
	at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
	at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by riverszhang89** [comment]
Did you get the cdb2jdbc library from `cdb2jdbc/build/libs`, or from `~/.m2/repository/com/bloomberg/comdb2/cdb2jdbc/2.0.0/`?

**Comment by riverszhang89** [comment]
It seems that the protobuf-java version we declared in gradle and maven do not match 😟

**Comment by saatviks** [comment]
From gradle - I'll just modify the version of protobuf-java in build.gradle and get the new `cdb2jdbc` jar. I guess that should be fine?

**Comment by riverszhang89** [comment]
It should work. Or you could simply use `~/.m2/repository/com/bloomberg/comdb2/cdb2jdbc/2.0.0/cdb2jdbc-2.0.0.jar`

**Comment by saatviks** [comment]
I think `protobuf-java-3.4.0` is needed. The reason I used `gradle` was because my maven builds(`mvn install`) were failing. Now when I tried changing the version in `build.gradle` - `./gradlew install` gives this error log:
```
/Users/saatvik/ExtraCredit/comdb2/cdb2jdbc/build/generated-sources/main/java/Bpfunc.java:6290: error: no suitable method found for parseFrom(ByteBuffer,ExtensionRegistryLite)
      return PARSER.parseFrom(data, extensionRegistry);
                   ^
    method Parser.parseFrom(CodedInputStream,ExtensionRegistryLite) is not applicable
      (argument mismatch; ByteBuffer cannot be converted to CodedInputStream)
    method Parser.parseFrom(ByteString,ExtensionRegistryLite) is not applicable
      (argument mismatch; ByteBuffer cannot be converted to ByteString)
    method Parser.parseFrom(byte[],ExtensionRegistryLite) is not applicable
      (argument mismatch; ByteBuffer cannot be converted to byte[])
    method Parser.parseFrom(InputStream,ExtensionRegistryLite) is not applicable
      (argument mismatch; ByteBuffer cannot be converted to InputStream)
```

**Comment by riverszhang89** [comment]
I think you'd need to change the version in build.gradle from 3.4.0 to 3.2.0 in order to match the version in pom.xml, and use protobuf-java 3.2.0 instead. Could you also run `./gradlew clean install`? The JDBC driver does not need bpfunc. I have no idea why gradle complained there.

**Comment by saatviks** [comment]
So, I should back up a little: When I first tried building a jar, I did so with Maven. But it gave me an error while compiling. This is why I tried gradle which worked. Just now when I did change the version in build.gradle from 3.4.0 to 3.2.0 - gradle started throwing the same error Maven was throwing earlier.
Thus, I realized that the issue is that the version of protobuf expected when compiling to the jar is `3.4.0`. When I changed from 3.2.0 to 3.4.0 in Maven, the earlier error disappeared and I got the uber-jar in `target/`.

**Comment by riverszhang89** [comment]
Ah I see. By default the protobuf-gradle plugin includes all `*.proto` files under `$srcDir` ([docs](https://github.com/google/protobuf-gradle-plugin#cutomizing-source-directories)), therefore bpfunc is also compiled. I will fix it in a bit.

**Comment by riverszhang89** [comment]
Any luck with the uber jar?

**Comment by saatviks** [comment]
I did get the uber-jar from Maven and yes it seems to be working :+1:.

**Comment by riverszhang89** [comment]
Awesome. Thank you!
