### ISSUE TITLE
Segfault when executing a DDL statement with enable_sql_stmt_caching

### ISSUE THREAD

**Issue by riverszhang89** [bloomberg/comdb2#578]
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffab09e700 (LWP 15987)]
0x0000000000597777 in touch_stmt_entry (thd=0x7fffab09da70, entry=0x0) at /home/admin/pr/db/sqlinterfaces.c:2710
2710        if (entry->params_to_bind) {
(gdb) bt
#0  0x0000000000597777 in touch_stmt_entry (thd=0x7fffab09da70, entry=0x0) at /home/admin/pr/db/sqlinterfaces.c:2710
#1  0x000000000059a886 in put_prepared_stmt_int (thd=0x7fffab09da70, clnt=0x7fffb249bb40, rec=0x7fffab09d7d0, outrc=0) at /home/admin/pr/db/sqlinterfaces.c:3894
#2  0x000000000059a9b5 in put_prepared_stmt (thd=0x7fffab09da70, clnt=0x7fffb249bb40, rec=0x7fffab09d7d0, outrc=0) at /home/admin/pr/db/sqlinterfaces.c:3923
#3  0x000000000059efd4 in sqlite_done (thd=0x7fffab09da70, clnt=0x7fffb249bb40, rec=0x7fffab09d7d0, outrc=0) at /home/admin/pr/db/sqlinterfaces.c:5581
#4  0x000000000059f40f in handle_sqlite_requests (thd=0x7fffab09da70, clnt=0x7fffb249bb40, comm=0xd31640 <client_sql_api>) at /home/admin/pr/db/sqlinterfaces.c:5695
#5  0x000000000059f54f in execute_sql_query (thd=0x7fffab09da70, clnt=0x7fffb249bb40) at /home/admin/pr/db/sqlinterfaces.c:5743
#6  0x00000000005a00a1 in sqlengine_work_appsock (thddata=0x7fffab09da70, work=0x7fffb249bb40) at /home/admin/pr/db/sqlinterfaces.c:6044
#7  0x00000000005a01e5 in sqlengine_work_appsock_pp (pool=0x5ad9010, work=0x7fffb249bb40, thddata=0x7fffab09da70, op=0) at /home/admin/pr/db/sqlinterfaces.c:6077
#8  0x00000000006ef849 in thdpool_thd (voidarg=0x5be7030) at /home/admin/pr/bb/thdpool.c:708
#9  0x00000000006d653c in thr_func (arg=0x5af3050) at /home/admin/pr/bb/comdb2_pthread_create.c:235
#10 0x00007ffff6618064 in start_thread (arg=0x7fffab09e700) at pthread_create.c:309
#11 0x00007ffff634d62d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) p entry
$1 = (stmt_hash_entry_type *) 0x0
```
The bug is reported by @saatviks. @nirbhayc Would you mind taking a look?

**Comment by riverszhang89** [comment]
Fixed in https://github.com/bloomberg/comdb2/commit/dd1783c8e26b5e57a2c48bbb2d3128b7ac99dcda.
