### ISSUE TITLE
Failed to get peer address

### ISSUE THREAD

**Issue by QinyuHu** [bloomberg/comdb2#585]
I am trying to run TPCH benchmarks on Comdb2. And calling .execute("DELETE FROM Customer") I encountered the following errors. What should I do to solve this?

     [java] 	at com.bloomberg.comdb2.jdbc.SockIO.open(SockIO.java:130)
     [java] 	at com.bloomberg.comdb2.jdbc.SockIO.write(SockIO.java:73)
     [java] 	at com.bloomberg.comdb2.jdbc.SockIO.write(SockIO.java:81)
     [java] 	at com.bloomberg.comdb2.jdbc.Comdb2Handle.reopen(Comdb2Handle.java:1795)
     [java] 	at com.bloomberg.comdb2.jdbc.Comdb2Handle.open(Comdb2Handle.java:1618)
     [java] 	at com.bloomberg.comdb2.jdbc.Comdb2Handle.runStatementInt(Comdb2Handle.java:911)
     [java] 	at com.bloomberg.comdb2.jdbc.Comdb2Handle.runStatement(Comdb2Handle.java:1342)
     [java] 	at com.bloomberg.comdb2.jdbc.Comdb2Handle.runStatement(Comdb2Handle.java:751)
     [java] 	at com.bloomberg.comdb2.jdbc.Comdb2Statement.executeQuery(Comdb2Statement.java:118)
     [java] 	at com.bloomberg.comdb2.jdbc.Comdb2Statement.executeQuery(Comdb2Statement.java:70)
     [java] 	at com.bloomberg.comdb2.jdbc.Comdb2Statement.execute(Comdb2Statement.java:232)

2017/12/13 22:01:30 [ERROR] accept_thread: timeout reading from socket, peeraddr=127.0.0.1
2017/12/13 22:01:30 [ERROR] accept_thread: timeout reading from socket, peeraddr=127.0.0.1
2017/12/13 22:01:30 [ERROR] accept_thread: timeout reading from socket, peeraddr=127.0.0.1
2017/12/13 22:01:30 [ERROR] accept_thread: timeout reading from socket, peeraddr=127.0.0.1
clnt is 0x6862b10, sql is begin
2017/12/13 22:01:30 [ERROR] read_newsql_query: Invalid message  1852143475
2017/12/13 22:01:30 [ERROR] accept_thread: timeout reading from socket, peeraddr=127.0.0.1
2017/12/13 22:01:30 [ERROR] Failed to get peer address

**Comment by adizaimi** [comment]
are you trying to delete everything from that table?
you probably want to do 'truncate Customer' for instantaneous emptying of a table.

**Comment by QinyuHu** [comment]
Is 'truncate Customer' same as "DELETE FROM Customer"?

But the issue seems from peeraddr? What does "Failed to get peer address" mean?

**Comment by riverszhang89** [comment]
See [Netpoll](https://bloomberg.github.io/comdb2/op.html#netpoll) for more information.

**Comment by adizaimi** [comment]
> Is 'truncate Customer' same as "DELETE FROM Customer"?
The same in outcome, much much faster if you just want to delete all entries in the table.

**Comment by QinyuHu** [comment]
I got a new question:
Is Comdb2 mainly focus on OLTP? I feel the data size generated by TPCH looks too big for Comdb2 (I have to set maxosqltransfer 100000000 just for loading 1 table).

Also, after loading, I encountered this following error:

2017/12/13 21:14:08 [ERROR] Master (null) failed to acknowledge session 1 a0784c62-b993-42b0-84bb-40f55be368e5
2017/12/13 21:14:08 [ERROR] sqlengine entering wrong state from /home/comdb2/db/sqlinterfaces.c line 1933.

**Comment by QinyuHu** [comment]
I got a new question:
Is Comdb2 mainly focus on OLTP? I feel the data size generated by TPCH looks too big for Comdb2 (I have to set maxosqltransfer 100000000 just for loading 1 table).
  
  

Also, after loading with 1 thread, I encountered this following error:

2017/12/13 21:14:08 [ERROR] Master (null) failed to acknowledge session 1 a0784c62-b993-42b0-84bb-40f55be368e5
2017/12/13 21:14:08 [ERROR] sqlengine entering wrong state from /home/comdb2/db/sqlinterfaces.c line 1933.

**Comment by riverszhang89** [comment]
Your 1st question - Let's try to change the netpoll at runtime instead:

Before loading the data, you'd run:

```
cdb2sql your_database 'exec procedure sys.cmd.send("netpoll 5000")'
```

You should be able to get back the output below.

```
(out='Setting net accept-poll to 5000 ms.')
```

About your 2nd question, database size is never a problem for Comdb2. However, one might still want to limit the number of modifications allowed per transaction to improve the concurrency - The more changes a transaction makes, the more locks the transaction needs, the more likely other transactions are blocked. And 50000 seems a reasonable default limit. Also `maxosqltransfer 100,000,000` isn't a crazy large value - try increasing it to 1 billion.

**Comment by QinyuHu** [comment]
Thanks, this line `cdb2sql your_database 'exec procedure sys.cmd.send("netpoll 5000")'` works.

But even after setting netpoll to 50,000ms, still the same issue. Should I try even bigger value?
```
2017/12/14 11:24:42 [ERROR] read_stream: Connection reset by peer
2017/12/14 11:24:42 [ERROR] accept_thread: read_stream failed for = <unknown>
2017/12/14 11:24:42 [ERROR] Failed to get peer address
2017/12/14 11:24:42 [ERROR] read_stream: Connection reset by peer
2017/12/14 11:24:42 [ERROR] accept_thread: read_stream failed for = <unknown>
2017/12/14 11:24:42 [ERROR] Failed to get peer address
2017/12/14 11:24:42 [ERROR] read_stream: Connection reset by peer
2017/12/14 11:24:42 [ERROR] accept_thread: read_stream failed for = <unknown>
2017/12/14 11:24:42 [ERROR] Failed to get peer address
2017/12/14 11:24:42 [ERROR] read_newsql_query: Invalid message  1852143475
2017/12/14 11:24:42 [ERROR] read_stream: Connection reset by peer
2017/12/14 11:24:42 [ERROR] accept_thread: read_stream failed for = <unknown>
2017/12/14 11:24:42 [ERROR] Failed to get peer address
2017/12/14 11:24:42 [ERROR] sqlengine entering wrong state from /home/tangy/extra_credit/comdb2/db/sqlinterfaces.c line 1948.
```
And if I directly try same thing - loading data the second time, I got this
```
2017/12/14 11:27:23 [ERROR] sql_update_usertran_state CLNT 0x5fffb10 I AM ALREADY IN TRANS
2017/12/14 11:27:23 [ERROR] sqlengine entering wrong state from /home/tangy/extra_credit/comdb2/db/sqlinterfaces.c line 1917.
2017/12/14 11:27:23 [ERROR] shadow_tran not cleared, aborting
2017/12/14 11:27:23 [ERROR] sess_blocksock field is not cleared!
2017/12/14 11:27:23 [ERROR] 0x5fffb10 rqid 1 in USE! 100669184
```
And after the above (second try), I cannot set netpoll because of the following error:
```
cdb2_open rc -1 cdb2_get_dbhosts: can't do dbinfo query on tpch hosts.
```

**Comment by riverszhang89** [comment]
Nope. You got a different error after the netpoll change (by the way, it should be "net_poll 5000" in the LRL. I missed the underscore there):

```2017/12/14 11:24:42 [ERROR] read_stream: Connection reset by peer```

It means that your application deliberately closed the connection to the database.

**Comment by riverszhang89** [comment]
> which looks like the database I created (tpch) crashed

Do you have a callstack of the crash by any chance?

**Comment by QinyuHu** [comment]
I am trying to understand what happened now. I cannot isolate the above two issues, so I am trying to run 1 thread loading Customers table only. All looks fine until finishing and I got this Exception: (I have posted this Exception above; currently only this issue I can reproduce it everytime, other issues I don't have a clue for right now.)
```
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to load the TPCH database
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:340)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:293)
	at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:799)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:539)
Caused by: java.sql.SQLNonTransientException: [RC = -8] sqlinterfaces: wrong sql handle state

	at com.bloomberg.comdb2.jdbc.Comdb2Connection.createSQLException(Comdb2Connection.java:720)
	at com.bloomberg.comdb2.jdbc.Comdb2Connection.commit(Comdb2Connection.java:357)
	at com.oltpbenchmark.benchmarks.tpch.TPCHLoader.load(TPCHLoader.java:226)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:329)
	... 3 more
```
And in DB side I got this
```
2017/12/14 13:26:49 [ERROR] Master (null) failed to acknowledge session 1 33d40c5d-eb57-4d1f-a8f3-ef89e65610e4
2017/12/14 13:26:49 [ERROR] sqlengine entering wrong state from /home/tangy/extra_credit/comdb2/db/sqlinterfaces.c line 1933.
```

**Comment by QinyuHu** [comment]
And if I using 1 thread to read a much bigger table - LineItems (10 times bigger than Customer), I will encounter this (`maxosqltransfer 1,000,000,000`)
```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE$column$1.parsePartialFrom(Sqlresponse.java:4990)
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE$column$1.parsePartialFrom(Sqlresponse.java:4985)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:874)
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE.<init>(Sqlresponse.java:4201)
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE.<init>(Sqlresponse.java:4134)
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE$2.parsePartialFrom(Sqlresponse.java:7537)
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE$2.parsePartialFrom(Sqlresponse.java:7532)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE.parseFrom(Sqlresponse.java:6142)
	at com.bloomberg.comdb2.jdbc.ProtobufProtocol.unpackSqlResp(ProtobufProtocol.java:85)
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.readRecord(Comdb2Handle.java:701)
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.next_int(Comdb2Handle.java:1473)
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.runStatementInt(Comdb2Handle.java:1257)
	at com.bloomberg.comdb2.jdbc.Comdb2Handle.runStatement(Comdb2Handle.java:1342)
	at com.bloomberg.comdb2.jdbc.Comdb2Statement.executeQuery(Comdb2Statement.java:133)
	at com.bloomberg.comdb2.jdbc.Comdb2Statement.executeQuery(Comdb2Statement.java:70)
	at com.bloomberg.comdb2.jdbc.Comdb2Statement.executeUpdate(Comdb2Statement.java:157)
	at com.bloomberg.comdb2.jdbc.Comdb2PreparedStatement.executeUpdate(Comdb2PreparedStatement.java:132)
	at com.bloomberg.comdb2.jdbc.Comdb2PreparedStatement.executeBatch(Comdb2PreparedStatement.java:437)
	at com.oltpbenchmark.benchmarks.tpch.TPCHLoader$TableLoader.run(TPCHLoader.java:486)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to load the TPCH database
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:340)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:293)
	at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:799)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:539)
Caused by: java.sql.SQLNonTransientException: [RC = -8] sqlinterfaces: wrong sql handle state

	at com.bloomberg.comdb2.jdbc.Comdb2Connection.createSQLException(Comdb2Connection.java:720)
	at com.bloomberg.comdb2.jdbc.Comdb2Connection.commit(Comdb2Connection.java:357)
	at com.oltpbenchmark.benchmarks.tpch.TPCHLoader.load(TPCHLoader.java:226)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:329)
	... 3 more
```

**Comment by riverszhang89** [comment]
```2017/12/14 13:36:24 LONG REQUEST 887768 MS logged in /home/tangy/comdb2/var/log/cdb2/tpch.longreqs [SOCKSQL num=1 tot=[312 312] rtt=[312 312] rtrs=[0 0]]```

It is a friendly warning on long requests. It is not necessarily a problem.

I'm a bit confused - by "read a much bigger table", do you actually mean loading the data from whatever source you've got into Comdb2?

**Comment by QinyuHu** [comment]
By "read a much bigger table" - I might misunderstood something, just point me out - It is not any sources but all created by tpch-dbgen: 
I am loading tables from corresponding .tbl file one by one for TPC-H test purpose. There are in total 8 .tbl files and I created 8 schemas and trying to load the data into empty table.
Here is the size of each .tbl file created by dbgen
```
-rw-rw-r-- 1 tangy tangy   97684197 Dec 13 00:35 tpch/dbgen/customer.tbl
-rw-rw-r-- 1 tangy tangy 3085874988 Dec 13 00:35 tpch/dbgen/lineitem.tbl
-rw-rw-r-- 1 tangy tangy       2224 Dec 13 00:35 tpch/dbgen/nation.tbl
-rw-rw-r-- 1 tangy tangy  695415470 Dec 13 00:35 tpch/dbgen/orders.tbl
-rw-rw-r-- 1 tangy tangy  479604970 Dec 13 00:35 tpch/dbgen/partsupp.tbl
-rw-rw-r-- 1 tangy tangy   96874657 Dec 13 00:35 tpch/dbgen/part.tbl
-rw-rw-r-- 1 tangy tangy        389 Dec 13 00:35 tpch/dbgen/region.tbl
-rw-rw-r-- 1 tangy tangy    5669995 Dec 13 00:35 tpch/dbgen/supplier.tbl
```
And currently error I encountered:
1. I cannot run multiple threads (each thread read 1 .tbl) at the same time (not sure about this so just leave it for now).
2. To read .tbl using 1 thread
2.1 Some small .tbl files works fine - Nation, Region
2.2 Some .tbl report this kind of error - Customers, Part, Partsupp
```
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to load the TPCH database
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:340)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:293)
	at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:799)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:539)
Caused by: java.sql.SQLNonTransientException: [RC = -8] sqlinterfaces: wrong sql handle state

	at com.bloomberg.comdb2.jdbc.Comdb2Connection.createSQLException(Comdb2Connection.java:720)
	at com.bloomberg.comdb2.jdbc.Comdb2Connection.commit(Comdb2Connection.java:357)
	at com.oltpbenchmark.benchmarks.tpch.TPCHLoader.load(TPCHLoader.java:226)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:329)
	... 3 more
```
2.3 Some report this kind of error - Lineitem, Orders
```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE$column$1.parsePartialFrom(Sqlresponse.java:4990)
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE$column$1.parsePartialFrom(Sqlresponse.java:4985)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:874)
	at com.bloomberg.comdb2.jdbc.Sqlresponse$CDB2_SQLRESPONSE.<init>(Sqlresponse.java:4201)
...(see above)
```

All these .tbl are generated by tpch-dbgen. From my view they just have different sizes.

**Comment by riverszhang89** [comment]
Are you batching the inserts? If so, you'd need to lower the batch size, or increase JVM heap size (-Xmx).

**Comment by QinyuHu** [comment]
Which issue will this solve?
"lower the batch size, or increase JVM heap size (-Xmx)."

**Comment by riverszhang89** [comment]
This: `Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded`.

I don't quite understand the `failed to acknowledge session` and `sqlengine entering wrong state` errors yet. But I have a feeling that they were caused by the OOM error on the client side.

**Comment by QinyuHu** [comment]
Any suggestions that how can I isolate this?

**Comment by riverszhang89** [comment]
Unclear. Can you please increase -Xmx? Maybe those error will then go away.

**Comment by QinyuHu** [comment]
For the OOM I increased the heap size to 10 GB and also disabled the GC exception but it still stuck somewhere while loading Orders.
`export ANT_OPTS="-XX:-UseGCOverheadLimit -Xmx10g"`

**Comment by riverszhang89** [comment]
To help us diagnose the problem, can you please tell us what exceptions/errors you saw?

**Comment by QinyuHu** [comment]
Hi, we might need to set this asides for sometime because of other course work. We will reach back to you as soon as we finish finals if some other issues arouse.
