### ISSUE TITLE
Time partition and FKs

### ISSUE THREAD

**Issue by nirbhayc** [bloomberg/comdb2#835]
```
nctdb> create table t1(i int primary key)$$
nctdb> create table t2(i int primary key, foreign key (i) references t1(i) on delete c
ascade)$$
nctdb> insert into t1 values(1);
nctdb> insert into t2 values(1);
nctdb> create time partition on t1 as t1_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC';
```
Error logs:
```
[ERROR] Schema change error: Can't drop tables with foreign constraints
[ERROR] >>> SCHEMA CHANGE ERROR: TABLE t1, RC -1
[ERROR] _view_cron_phase3: phase 3 failed rc=-4 errstr=failed to drop table
[ERROR] Schedule timepart_cron error event 1524884395 rc=-4 errstr=failed to drop table
```
Though DROP sc fails because of the referencing FK, IMHO, the creation of time partition on the referenced table should have detected the FK and failed in first place. On the same grounds, trying to add a FK that references a time-partitioned table, should fail too.

**Comment by nirbhayc** [comment]
I'm seeing more strange behaviors:
```
nctdb> select * from comdb2_tables;
(tablename='sqlite_stat1')
(tablename='sqlite_stat4')
[select * from comdb2_tables] rc 0
nctdb> create table t1(i int primary key)$$
[create table t1(i int primary key)] rc 0
nctdb> create table t2(i int primary key, foreign key (i) references t1(i) on delete cascade)$$
[create table t2(i int primary key, foreign key (i) references t1(i) on delete cascade)] rc 0
nctdb> insert into t1 values(1);
(rows inserted=1)
[insert into t1 values(1)] rc 0
nctdb> insert into t2 values(1);
(rows inserted=1)
[insert into t2 values(1)] rc 0
nctdb> create time partition on t1 as t1_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC';
[create time partition on t1 as t1_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC'] rc 0

# ^^^^ rc 0 ??
# [ERROR] Schema change error: Can't drop tables with foreign constraints
# [ERROR] >>> SCHEMA CHANGE ERROR: TABLE t1, RC -1
# [ERROR] _view_cron_phase3: phase 3 failed rc=-4 errstr=failed to drop table
# [ERROR] Schedule timepart_cron error event 1524884395 rc=-4 errstr=failed to drop table  

nctdb>
nctdb> select * from comdb2_tables;
(tablename='sqlite_stat1')
(tablename='sqlite_stat4')
(tablename='t1')
(tablename='t2')
(tablename='t10')
(tablename='t12')
(tablename='t11')
[select * from comdb2_tables] rc 0
nctdb> select * from comdb2_timepartitions;
(name='t1_tp', period='test2min', retention=2, nshards=2, version=0, shard0name='t1', starttime=1524884270, sourceid='865c0042-ba83-4070-8fef-a0d81f93efdf')
[select * from comdb2_timepartitions] rc 0
nctdb> insert into t10 values(1);
(rows inserted=1)
[insert into t10 values(1)] rc 0
nctdb> insert into t11 values(1);
(rows inserted=1)
[insert into t11 values(1)] rc 0
nctdb> insert into t12 values(1);
(rows inserted=1)
[insert into t12 values(1)] rc 0
nctdb> select * from t1;
(i=1)
[select * from t1] rc 0
nctdb> select * from t2;
(i=1)
[select * from t2] rc 0
nctdb> insert into t11 values(10);
[insert into t11 values(10)] failed with rc 2 unable to add record rc = 4
nctdb> insert into t11 values(12);
[insert into t11 values(12)] failed with rc 304 no such table "t11"
nctdb> insert into t11 values(12);
(rows inserted=1)
[insert into t11 values(12)] rc 0
nctdb> insert into t11 values(13);
(rows inserted=1)
[insert into t11 values(13)] rc 0
```

**Comment by riverszhang89** [comment]
```
(gdb) t 17
[Switching to thread 17 (Thread 0x7fffe8e7c700 (LWP 27816))]
#0  pthread_rwlock_wrlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S:85
85      ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S: No such file or directory.
(gdb) bt
#0  pthread_rwlock_wrlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S:85
#1  0x00000000005dd75c in wrlock_schema_int (file=0x9d39c8 "/home/admin/pr/schemachange/sc_logic.c", func=0x9d4397 <__func__.35817> "do_ddl", line=377) at /home/admin/pr/bbinc/schema_lk.h:74
#2  0x00000000005de375 in do_ddl (pre=0x5f4fef <do_drop_table>, post=0x5f50c8 <finalize_drop_table>, iq=0x7ffff7f7a5b8, s=0x7fffe8e7b2f0, tran=0x0, type=drop) at /home/admin/pr/schemachange/sc_logic.c:377
#3  0x00000000005de849 in do_schema_change_tran (arg=0x7a47e78) at /home/admin/pr/schemachange/sc_logic.c:490
#4  0x00000000005decda in do_schema_change (s=0x7fffe8e7b2f0) at /home/admin/pr/schemachange/sc_logic.c:569
#5  0x00000000005f31d6 in sc_timepart_drop_table (tableName=0x7a416f0 "t10", xerr=0x7fffe8e7bb00) at /home/admin/pr/schemachange/schemachange.c:1163
#6  0x00000000005c7585 in _views_rollout_phase3 (oldestShardName=0x7a416f0 "t10", err=0x7fffe8e7bb00) at /home/admin/pr/db/views.c:1846
#7  0x00000000005c6799 in _view_cron_phase3 (source_id=0x7a41a20 "\026D\307\004I\247A\220\231\213\346\235.\227\315V\030~\244\a", arg1=0x7a416f0, arg2=0x0, arg3=0x0, err=0x7fffe8e7bb00) at /home/admin/pr/db/views.c:1438
#8  0x00000000005cd366 in _cron_runner (arg=0x7ffff7f782e8) at /home/admin/pr/db/views_cron.c:253
#9  0x00007ffff6410064 in start_thread (arg=0x7fffe8e7c700) at pthread_create.c:309
#10 0x00007ffff614562d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) f 1
#1  0x00000000005dd75c in wrlock_schema_int (file=0x9d39c8 "/home/admin/pr/schemachange/sc_logic.c", func=0x9d4397 <__func__.35817> "do_ddl", line=377) at /home/admin/pr/bbinc/schema_lk.h:74
74          int rc = pthread_rwlock_wrlock(&schema_lk);
(gdb) t 29
[Switching to thread 29 (Thread 0x7fffe78c1700 (LWP 27828))]
#0  pthread_rwlock_rdlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_rdlock.S:87
87      ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_rdlock.S: No such file or directory.
(gdb) bt
#0  pthread_rwlock_rdlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_rdlock.S:87
#1  0x00000000005c4594 in timepart_is_timepart (name=0x5f71cd8 "t1", lock=1) at /home/admin/pr/db/views.c:207
#2  0x00000000008ace64 in chkAndCopyTable (pParse=0x7fffe78bdcc0, dst=0x5f71cd8 "t1", name=0x5f57b61 "t1 as t2_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC'", max_length=3, mustexist=1)
    at /home/admin/pr/sqlite/comdb2build.c:139
#3  0x00000000008ad193 in chkAndCopyTableTokens (v=0x5f6ac50, pParse=0x7fffe78bdcc0, dst=0x5f71cd8 "t1", t1=0x5f6b3d0, t2=0x0, mustexist=1) at /home/admin/pr/sqlite/comdb2build.c:240
#4  0x00000000008af32c in comdb2CreateTimePartition (pParse=0x7fffe78bdcc0, table=0x5f6b3d0, partition_name=0x5f6b410, period=0x5f6b450, retention=0x5f6b490, start=0x5f6b4d0) at /home/admin/pr/sqlite/comdb2build.c:961
#5  0x000000000095cf72 in yy_reduce (yypParser=0x5f6b2f8, yyruleno=305) at parse.y:1906
#6  0x000000000095df68 in sqlite3Parser (yyp=0x5f6b2f8, yymajor=1, yyminor=..., pParse=0x7fffe78bdcc0) at parse.c:5367
#7  0x00000000008fb0d4 in sqlite3RunParser (pParse=0x7fffe78bdcc0, zSql=0x5f57b48 "create time partition on t1 as t2_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC'", pzErrMsg=0x7fffe78c0648)
    at /home/admin/pr/sqlite/tokenize.c:549
#8  0x00000000008e3d05 in sqlite3Prepare (db=0x5f5db50, zSql=0x5f57b48 "create time partition on t1 as t2_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC'", nBytes=-1, saveSqlFlag=1, pReprepare=0x0,
    ppStmt=0x7fffe78c0868, pzTail=0x7fffe78c0790, flags=0) at /home/admin/pr/sqlite/prepare.c:701
#9  0x00000000008e4098 in sqlite3LockAndPrepare (db=0x5f5db50, zSql=0x5f57b48 "create time partition on t1 as t2_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC'", nBytes=-1, saveSqlFlag=1, pOld=0x0,
    ppStmt=0x7fffe78c0868, pzTail=0x7fffe78c0790, flags=0) at /home/admin/pr/sqlite/prepare.c:801
#10 0x00000000008e43af in sqlite3_prepare_v2 (db=0x5f5db50, zSql=0x5f57b48 "create time partition on t1 as t2_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC'", nBytes=-1, ppStmt=0x7fffe78c0868,
    pzTail=0x7fffe78c0790) at /home/admin/pr/sqlite/prepare.c:934
#11 0x000000000058c7c8 in get_prepared_stmt_int (thd=0x7fffe78c0af0, clnt=0x7fffe78f0c70, rec=0x7fffe78c0860, err=0x7fffe78c0910, recreate=1) at /home/admin/pr/db/sqlinterfaces.c:2845
#12 0x000000000058c9a0 in get_prepared_stmt (thd=0x7fffe78c0af0, clnt=0x7fffe78f0c70, rec=0x7fffe78c0860, err=0x7fffe78c0910) at /home/admin/pr/db/sqlinterfaces.c:2886
#13 0x000000000058cd7e in get_prepared_bound_stmt (thd=0x7fffe78c0af0, clnt=0x7fffe78f0c70, rec=0x7fffe78c0860, err=0x7fffe78c0910) at /home/admin/pr/db/sqlinterfaces.c:2973
#14 0x000000000058e1c4 in handle_sqlite_requests (thd=0x7fffe78c0af0, clnt=0x7fffe78f0c70) at /home/admin/pr/db/sqlinterfaces.c:3483
#15 0x000000000058e4fa in execute_sql_query (thd=0x7fffe78c0af0, clnt=0x7fffe78f0c70) at /home/admin/pr/db/sqlinterfaces.c:3577
#16 0x000000000058f05d in sqlengine_work_appsock (thddata=0x7fffe78c0af0, work=0x7fffe78f0c70) at /home/admin/pr/db/sqlinterfaces.c:3883
#17 0x000000000058f1a1 in sqlengine_work_appsock_pp (pool=0x5a9a088, work=0x7fffe78f0c70, thddata=0x7fffe78c0af0, op=0) at /home/admin/pr/db/sqlinterfaces.c:3916
#18 0x00000000006dbc91 in thdpool_thd (voidarg=0x5f56380) at /home/admin/pr/bb/thdpool.c:708
#19 0x00007ffff6410064 in start_thread (arg=0x7fffe78c1700) at pthread_create.c:309
#20 0x00007ffff614562d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

SQL thread and view thread deadlock each other.

**Comment by dorinhogea** [comment]
FK-s are not supported for time partitions.  We should prevent creating a time partition on a table with FK-s, and prevent adding FK-s to an existing time partition.

**Comment by nirbhayc** [comment]
@dorinhogea : Also, is there a use case for creating time partition with starttime pointing in past? If not, perhaps its good idea to prevent that as well. I mistakenly ran this command with starttime pointing in past with 'test2min' period creating thousands of timepart tables, substantially slowing down the server.

**Comment by dorinhogea** [comment]
@nirbhayc: what test do you have in mind? it is normal to create time partitions with starttime in the past; the server will roll out until it gets to present.

**Comment by nirbhayc** [comment]
```
nctdb> create table t1(i int primary key)$$
[create table t1(i int primary key)] rc 0
nctdb> create table t2(i int primary key, foreign key (i) references t1(i) on delete cascade)$$
[create table t2(i int primary key, foreign key (i) references t1(i) on delete cascade)] rc 0
nctdb> insert into t1 values(1);
(rows inserted=1)
[insert into t1 values(1)] rc 0
nctdb> insert into t2 values(1);
(rows inserted=1)
[insert into t2 values(1)] rc 0
nctdb> create time partition on t1 as t1_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC';
[create time partition on t1 as t1_tp period 'test2min' retention 2 start '2018-04-28T025750 UTC'] rc 0
```

**Comment by dorinhogea** [comment]
Yes, don't do that; running schema changes in a loop will impact the speed of your database.  It is ok to create db with start in the past.  Also, bear in mind that test2min uses different rollout code, which probably breaks in certain cases.   It was only meant to test specific aspects of time partitions, for a time reasonable regression test case; any other use is unsupported.

**Comment by nirbhayc** [comment]
Did the old time trigger schema change in loop? If so, I don't like that. I know 'test2min' is for testing only, what I am more worried about is the number of files getting created for no useful reason.
```
nctdb> create time partition on t1 as t1_tp period 'daily' retention 2 start '1971-04-28T025750 UTC';
[create time partition on t1 as t1_tp period 'daily' retention 2 start '1971-04-28T025750 UTC'] rc 0
nctdb> select * from comdb2_tables;
(tablename='sqlite_stat1')
(tablename='sqlite_stat4')
(tablename='t1')
(tablename='t2')
(tablename='$2_EDD2AB7A')
(tablename='$0_A2BDF977')
(tablename='$1_7FC6B09')
[select * from comdb2_tables] rc 0

$ ls ..datadir.. | wc -l
2476
```
Also, IMO, the other (internal?) tables created around time partition should remain hidden. What say?

I tried to drop one and that resulted in a deadlock.
```
nctdb> drop table '$1_7FC6B09'; 
```

**Comment by dorinhogea** [comment]
yes, you should never use DDL against shards.

**Comment by dorinhogea** [comment]
There are advantages for shards to be real tables.  If you want to 'hide' them, you can do:
select * from comdb2_tables where tablename not in (select shardname from comdb2_timepartshards)

**Comment by dorinhogea** [comment]
This should be the result for a normal time partition.  If you can reproduce the deadlock with non-test2min periods, please let me know.

c5 $ cdb2sql db1 local 'drop table "$0_43868980"'
[drop table "$0_43868980"] failed with rc -3 Shards cannot be schema changed independently

**Comment by dorinhogea** [comment]
FK issue addressed here:
https://github.com/bloomberg/comdb2/pull/867
